apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
spec:
  tls:
    - hosts:
      - BACKEND_HOST
  rules:
  - host: BACKEND_HOST
    http:
      paths:
      - backend:
          service:
            name: backend
            port: 
              number: 8080

